# 如果是开发合并请求到主干，则会根据约定式提交创建一个 releasePR，是一个新版本合并请求。

name: release please

on:
  push:
    branches:
      - v*.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nvm
      - run: npm ci
      - run: npm run build
      - uses: peter-evans/create-pull-request@v4
        id: pr
        with:
          commit-message: 'chore: build dist'
          delete-branch: true
          title: dist pr
          body: dist pr
      - run: gh pr merge ${{ steps.pr.outputs.pull-request-number }} --merge --auto

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          bump-minor-pre-major: true

  create-version:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.release_created
    steps:
      - uses: actions/checkout@v2
      - uses: jacobsvante/tag-major-minor-action@v0
        with:
          major: ${{ needs.release.outputs.major }}
          minor: ${{ needs.release.outputs.minor }}
